-- VGC Usage Stats — PostgreSQL schema for Supabase
-- Run this in the Supabase SQL editor (Database → SQL Editor → New query).

-- ─── Tables ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tournaments (
  id          TEXT        PRIMARY KEY,
  name        TEXT        NOT NULL,
  date        TIMESTAMPTZ NOT NULL,
  location    TEXT,
  generation  INTEGER     NOT NULL,
  format      TEXT        NOT NULL,
  official    BOOLEAN     NOT NULL
);

CREATE TABLE IF NOT EXISTS players (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    TEXT NOT NULL,
  country TEXT
);

CREATE TABLE IF NOT EXISTS teams (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id     BIGINT NOT NULL REFERENCES players(id),
  tournament_id TEXT   NOT NULL REFERENCES tournaments(id),
  UNIQUE (player_id, tournament_id)
);

CREATE TABLE IF NOT EXISTS pokemon_sets (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id        BIGINT  NOT NULL REFERENCES teams(id),
  species        TEXT    NOT NULL,
  form           TEXT,
  item           TEXT,
  ability        TEXT,
  tera_type      TEXT,
  is_mega        BOOLEAN NOT NULL DEFAULT FALSE,
  invalid        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS moves (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_set_id BIGINT NOT NULL REFERENCES pokemon_sets(id),
  move_name      TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id TEXT    NOT NULL REFERENCES tournaments(id),
  round_number  INTEGER NOT NULL,
  table_number  INTEGER,
  phase         INTEGER
);

CREATE TABLE IF NOT EXISTS match_participants (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id  BIGINT  NOT NULL REFERENCES matches(id),
  player_id BIGINT  NOT NULL REFERENCES players(id),
  team_id   BIGINT  NOT NULL REFERENCES teams(id),
  score     INTEGER NOT NULL,
  UNIQUE (match_id, player_id)
);

CREATE TABLE IF NOT EXISTS tournament_standings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id TEXT    NOT NULL REFERENCES tournaments(id),
  player_id     BIGINT  NOT NULL REFERENCES players(id),
  team_id       BIGINT  NOT NULL REFERENCES teams(id),
  "placing"     INTEGER,
  wins          INTEGER NOT NULL DEFAULT 0,
  losses        INTEGER NOT NULL DEFAULT 0,
  ties          INTEGER NOT NULL DEFAULT 0,
  dropped       BOOLEAN DEFAULT FALSE,
  UNIQUE (tournament_id, player_id)
);

CREATE TABLE IF NOT EXISTS limitless_api_raw_data (
  id       TEXT  PRIMARY KEY REFERENCES tournaments(id) ON DELETE CASCADE,
  details  JSONB,
  standings JSONB,
  pairings  JSONB
);

CREATE TABLE IF NOT EXISTS ps_usage_stats (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month         TEXT             NOT NULL,
  format        TEXT             NOT NULL,
  elo_cutoff    INTEGER          NOT NULL,
  rank          INTEGER          NOT NULL,
  species       TEXT             NOT NULL,
  usage_pct     DOUBLE PRECISION NOT NULL,
  raw_count     INTEGER          NOT NULL,
  total_battles INTEGER          NOT NULL,
  UNIQUE (month, format, elo_cutoff, species)
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_tournaments_date               ON tournaments(date);
CREATE INDEX IF NOT EXISTS idx_tournaments_format             ON tournaments(format);
CREATE INDEX IF NOT EXISTS idx_tournaments_generation_format  ON tournaments(generation, format);
CREATE INDEX IF NOT EXISTS idx_teams_tournament               ON teams(tournament_id);
CREATE INDEX IF NOT EXISTS idx_teams_player                   ON teams(player_id);
CREATE INDEX IF NOT EXISTS idx_pokemon_sets_team              ON pokemon_sets(team_id);
CREATE INDEX IF NOT EXISTS idx_pokemon_sets_species           ON pokemon_sets(species);
CREATE INDEX IF NOT EXISTS idx_moves_pokemon_set              ON moves(pokemon_set_id);
CREATE INDEX IF NOT EXISTS idx_matches_tournament             ON matches(tournament_id);
CREATE INDEX IF NOT EXISTS idx_matches_tournament_phase       ON matches(tournament_id, phase);
CREATE INDEX IF NOT EXISTS idx_match_participants_match       ON match_participants(match_id);
CREATE INDEX IF NOT EXISTS idx_match_participants_team        ON match_participants(team_id);
CREATE INDEX IF NOT EXISTS idx_tournament_standings_tournament ON tournament_standings(tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_standings_player    ON tournament_standings(player_id);

CREATE INDEX IF NOT EXISTS idx_ps_usage_stats_month_format    ON ps_usage_stats(month, format);
CREATE INDEX IF NOT EXISTS idx_ps_usage_stats_species         ON ps_usage_stats(species);

CREATE INDEX IF NOT EXISTS idx_pokemon_sets_item_lower        ON pokemon_sets(LOWER(item));
CREATE INDEX IF NOT EXISTS idx_pokemon_sets_species_lower     ON pokemon_sets(LOWER(species));

-- ─── Materialized views ───────────────────────────────────────────────────────
-- Caches expensive full-dataset queries. Refresh after each processor run via
-- the refresh_materialized_views() RPC.

CREATE MATERIALIZED VIEW IF NOT EXISTS pokemon_usage_mv AS
  WITH
  total AS (
    SELECT COUNT(*)::numeric AS n
    FROM teams t
    JOIN tournaments tour ON tour.id = t.tournament_id
    WHERE tour.format = 'M-A'
  ),
  tc_teams AS (
    WITH tc_phases AS (
      SELECT m.tournament_id, MAX(m.phase) AS max_phase
      FROM matches m
      JOIN tournaments t ON t.id = m.tournament_id
      WHERE t.format = 'M-A' AND m.phase IS NOT NULL
      GROUP BY m.tournament_id
      HAVING COUNT(DISTINCT m.phase) > 1
    )
    SELECT DISTINCT mp.team_id
    FROM match_participants mp
    JOIN matches m ON m.id = mp.match_id
    JOIN tc_phases tcp ON tcp.tournament_id = m.tournament_id AND m.phase = tcp.max_phase
  ),
  tc_mp AS (
    WITH tc_phases AS (
      SELECT m.tournament_id, MAX(m.phase) AS max_phase
      FROM matches m
      JOIN tournaments t ON t.id = m.tournament_id
      WHERE t.format = 'M-A' AND m.phase IS NOT NULL
      GROUP BY m.tournament_id
      HAVING COUNT(DISTINCT m.phase) > 1
    )
    SELECT mp.team_id, mp.score
    FROM match_participants mp
    JOIN matches m ON m.id = mp.match_id
    JOIN tc_phases tcp ON tcp.tournament_id = m.tournament_id AND m.phase = tcp.max_phase
  ),
  top_cut_total AS (SELECT COUNT(*)::numeric AS n FROM tc_teams),
  base AS (
    SELECT
      ps.species,
      BOOL_OR(ps.is_mega) AS is_mega,
      COUNT(DISTINCT t.id) AS teams,
      ROUND(SUM(mp.score) * 100.0 / NULLIF(COUNT(mp.score), 0), 2) AS win_rate
    FROM pokemon_sets ps
    JOIN teams t ON t.id = ps.team_id
    JOIN tournaments tour ON tour.id = t.tournament_id
    JOIN match_participants mp ON mp.team_id = t.id
    WHERE tour.format = 'M-A'
    GROUP BY ps.species
  ),
  top_cut AS (
    SELECT
      ps.species,
      COUNT(DISTINCT t.id) AS teams,
      ROUND(SUM(tcmp.score) * 100.0 / NULLIF(COUNT(tcmp.score), 0), 2) AS win_rate
    FROM pokemon_sets ps
    JOIN teams t ON t.id = ps.team_id
    JOIN tc_mp tcmp ON tcmp.team_id = t.id
    GROUP BY ps.species
  )
  SELECT
    b.species, b.is_mega, b.teams,
    ROUND(b.teams * 100.0 / total.n, 2)           AS usage_pct,
    b.win_rate,
    COALESCE(tc.teams, 0)                          AS top_cut_teams,
    ROUND(COALESCE(tc.teams, 0) * 100.0 / top_cut_total.n, 2) AS top_cut_usage,
    tc.win_rate                                    AS top_cut_wr
  FROM base b
  CROSS JOIN total CROSS JOIN top_cut_total
  LEFT JOIN top_cut tc ON tc.species = b.species
  ORDER BY b.teams DESC;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pokemon_usage_mv_species ON pokemon_usage_mv(species);

-- Matchups MV: precomputed species-vs-species win rates across all M-A matches.
-- Refreshed alongside pokemon_usage_mv; eliminates the slow join/aggregate that
-- caused >3s timeouts for popular species (issue #24).
CREATE MATERIALIZED VIEW IF NOT EXISTS pokemon_matchups_mv AS
WITH
ma_mp AS (
  SELECT mp.match_id, mp.team_id, mp.score
  FROM match_participants mp
  JOIN teams t ON t.id = mp.team_id
  JOIN tournaments tour ON tour.id = t.tournament_id
  WHERE tour.format = 'M-A'
),
match_sides AS (
  SELECT a.match_id, a.team_id AS team_a, a.score AS score_a, b.team_id AS team_b
  FROM ma_mp a
  JOIN ma_mp b ON b.match_id = a.match_id AND b.team_id != a.team_id
),
target_side AS (
  SELECT DISTINCT ms.match_id, ps.species AS target_species, ms.score_a AS target_score, ms.team_b AS opp_team
  FROM match_sides ms
  JOIN pokemon_sets ps ON ps.team_id = ms.team_a
),
matchup_pairs AS (
  SELECT DISTINCT ts.match_id, ts.target_species, ps.species AS opponent_species, ts.target_score
  FROM target_side ts
  JOIN pokemon_sets ps ON ps.team_id = ts.opp_team
)
SELECT
  target_species,
  opponent_species,
  COUNT(*)::BIGINT                                             AS matches,
  SUM(target_score)::BIGINT                                   AS wins,
  ROUND(SUM(target_score) * 100.0 / NULLIF(COUNT(*), 0), 2) AS win_rate
FROM matchup_pairs
GROUP BY target_species, opponent_species
HAVING COUNT(*) >= 10
ORDER BY target_species, matches DESC;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pokemon_matchups_mv_pk
  ON pokemon_matchups_mv(target_species, opponent_species);

-- Partners MV: precomputed co-usage and win rates for species pairs.
CREATE MATERIALIZED VIEW IF NOT EXISTS pokemon_partners_mv AS
WITH
ma_team_species AS (
  SELECT ps.species, t.id AS team_id
  FROM pokemon_sets ps
  JOIN teams t ON t.id = ps.team_id
  JOIN tournaments tour ON tour.id = t.tournament_id
  WHERE tour.format = 'M-A'
),
species_total AS (
  SELECT species, COUNT(DISTINCT team_id)::numeric AS n
  FROM ma_team_species
  GROUP BY species
),
duo_teams AS (
  SELECT a.species AS species_a, b.species AS species_b, a.team_id
  FROM ma_team_species a
  JOIN ma_team_species b ON b.team_id = a.team_id AND b.species != a.species
),
ma_mp AS (
  SELECT mp.team_id, mp.score
  FROM match_participants mp
  JOIN teams t ON t.id = mp.team_id
  JOIN tournaments tour ON tour.id = t.tournament_id
  WHERE tour.format = 'M-A'
)
SELECT
  dt.species_a                                                          AS species,
  dt.species_b                                                          AS partner_species,
  COUNT(DISTINCT dt.team_id)::BIGINT                                    AS teams,
  ROUND(COUNT(DISTINCT dt.team_id) * 100.0 / st.n, 2)                  AS usage_pct,
  ROUND(SUM(mp.score) * 100.0 / NULLIF(COUNT(mp.score), 0), 2)         AS win_rate
FROM duo_teams dt
JOIN species_total st ON st.species = dt.species_a
JOIN ma_mp mp ON mp.team_id = dt.team_id
GROUP BY dt.species_a, dt.species_b, st.n
HAVING COUNT(DISTINCT dt.team_id) >= 5
ORDER BY species, teams DESC;

CREATE UNIQUE INDEX IF NOT EXISTS idx_pokemon_partners_mv_pk
  ON pokemon_partners_mv(species, partner_species);

-- ─── Row-Level Security ───────────────────────────────────────────────────────
-- All normalized tables are publicly readable (anon key).
-- limitless_api_raw_data is admin-only (service_role bypasses RLS automatically).

ALTER TABLE tournaments           ENABLE ROW LEVEL SECURITY;
ALTER TABLE players               ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE pokemon_sets          ENABLE ROW LEVEL SECURITY;
ALTER TABLE moves                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches               ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_participants    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_standings  ENABLE ROW LEVEL SECURITY;
ALTER TABLE limitless_api_raw_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE ps_usage_stats         ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_read" ON tournaments;
DROP POLICY IF EXISTS "anon_read" ON players;
DROP POLICY IF EXISTS "anon_read" ON teams;
DROP POLICY IF EXISTS "anon_read" ON pokemon_sets;
DROP POLICY IF EXISTS "anon_read" ON moves;
DROP POLICY IF EXISTS "anon_read" ON matches;
DROP POLICY IF EXISTS "anon_read" ON match_participants;
DROP POLICY IF EXISTS "anon_read" ON tournament_standings;
DROP POLICY IF EXISTS "anon_read" ON ps_usage_stats;

CREATE POLICY "anon_read" ON tournaments          FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON players              FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON teams                FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON pokemon_sets         FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON moves                FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON matches              FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON match_participants   FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON tournament_standings FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON ps_usage_stats       FOR SELECT TO anon USING (true);
