const MEGA_ITEM_TO_MON: Record<string, string> = {
  'Abomasite':      'Abomasnow',
  'Absolite':       'Absol',
  'Aerodactylite':  'Aerodactyl',
  'Aggronite':      'Aggron',
  'Alakazite':      'Alakazam',
  'Altarianite':    'Altaria',
  'Ampharosite':    'Ampharos',
  'Audinite':       'Audino',
  'Beedrillite':    'Beedrill',
  'Blastoisinite':  'Blastoise',
  'Cameruptite':    'Camerupt',
  'Chandelurite':   'Chandelure',
  'Charizardite':   'Charizard',
  'Chesnaughtite':  'Chesnaught',
  'Chimechite':     'Chimecho',
  'Clefablite':     'Clefable',
  'Crabominite':    'Crabominable',
  'Delphoxite':     'Delphox',
  'Dragalgite':     'Dragalge',
  'Dragoninite':    'Dragonite',
  'Dragonitite':    'Dragonite',
  'Drampanite':     'Drampa',
  'Emboarite':      'Emboar',
  'Excadrite':      'Excadrill',
  'Feraligite':     'Feraligatr',
  'Feraligatrite':  'Feraligatr',
  'Floettite':      'Floette',
  'Froslassite':    'Froslass',
  'Galladite':      'Gallade',
  'Garchompite':    'Garchomp',
  'Gardevoirite':   'Gardevoir',
  'Gengarite':      'Gengar',
  'Glimmoranite':   'Glimmora',
  'Golurkite':      'Golurk',
  'Greninjite':     'Greninja',
  'Gyaradosite':    'Gyarados',
  'Hawluchanite':   'Hawlucha',
  'Heracronite':    'Heracross',
  'Houndoominite':  'Houndoom',
  'Kangaskhanite':  'Kangaskhan',
  'Lopunnite':      'Lopunny',
  'Lucarionite':    'Lucario',
  'Manectite':      'Manectric',
  'Mawilite':       'Mawile',
  'Medichamite':    'Medicham',
  'Meganiumite':    'Meganium',
  'Meowsticite':    'Meowstic',
  'Metagrossite':   'Metagross',
  'Pidgeotite':     'Pidgeot',
  'Pinsirite':      'Pinsir',
  'Raichunite':     'Raichu',
  'Sablenite':      'Sableye',
  'Salamencite':    'Salamence',
  'Scizorite':      'Scizor',
  'Scovillainite':  'Scovillain',
  'Sharpedonite':   'Sharpedo',
  'Skarmorite':     'Skarmory',
  'Slowbronite':    'Slowbro',
  'Starminite':     'Starmie',
  'Steelixite':     'Steelix',
  'Swampertite':    'Swampert',
  'Tyranitarite':   'Tyranitar',
  'Venusaurite':    'Venusaur',
  'Victreebelite':  'Victreebel',
};

export function megaItemToPokemon(item: string): string {
  // Strip X/Y/Z variant suffix (e.g. "Charizardite Y" → base "Charizardite", suffix " Y")
  const m = item.match(/^(.+?) ([XYZ])$/);
  const base = m ? m[1] : item;
  const variant = m ? ` ${m[2]}` : '';
  return (MEGA_ITEM_TO_MON[base] ?? item) + variant;
}
