-- VGC Usage Stats — PostgreSQL schema for Supabase
-- Run this in the Supabase SQL editor (Database → SQL Editor → New query).

-- ─── Tables ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tournaments (
  id          TEXT        PRIMARY KEY,
  name        TEXT        NOT NULL,
  date        TIMESTAMPTZ NOT NULL,
  location    TEXT,
  generation  INTEGER     NOT NULL,
  format      TEXT        NOT NULL,
  official    BOOLEAN     NOT NULL
);

CREATE TABLE IF NOT EXISTS players (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    TEXT NOT NULL,
  country TEXT
);

CREATE TABLE IF NOT EXISTS teams (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id     BIGINT NOT NULL REFERENCES players(id),
  tournament_id TEXT   NOT NULL REFERENCES tournaments(id),
  UNIQUE (player_id, tournament_id)
);

CREATE TABLE IF NOT EXISTS pokemon_sets (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id        BIGINT  NOT NULL REFERENCES teams(id),
  species        TEXT    NOT NULL,
  form           TEXT,
  item           TEXT,
  ability        TEXT,
  tera_type      TEXT,
  is_mega        BOOLEAN NOT NULL DEFAULT FALSE,
  invalid        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS moves (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_set_id BIGINT NOT NULL REFERENCES pokemon_sets(id),
  move_name      TEXT   NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id TEXT    NOT NULL REFERENCES tournaments(id),
  round_number  INTEGER NOT NULL,
  table_number  INTEGER,
  phase         INTEGER
);

CREATE TABLE IF NOT EXISTS match_participants (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id  BIGINT  NOT NULL REFERENCES matches(id),
  player_id BIGINT  NOT NULL REFERENCES players(id),
  team_id   BIGINT  NOT NULL REFERENCES teams(id),
  score     INTEGER NOT NULL,
  UNIQUE (match_id, player_id)
);

CREATE TABLE IF NOT EXISTS tournament_standings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id TEXT    NOT NULL REFERENCES tournaments(id),
  player_id     BIGINT  NOT NULL REFERENCES players(id),
  team_id       BIGINT  NOT NULL REFERENCES teams(id),
  "placing"     INTEGER,
  wins          INTEGER NOT NULL DEFAULT 0,
  losses        INTEGER NOT NULL DEFAULT 0,
  ties          INTEGER NOT NULL DEFAULT 0,
  dropped       BOOLEAN DEFAULT FALSE,
  UNIQUE (tournament_id, player_id)
);

CREATE TABLE IF NOT EXISTS limitless_api_raw_data (
  id       TEXT  PRIMARY KEY REFERENCES tournaments(id) ON DELETE CASCADE,
  details  JSONB,
  standings JSONB,
  pairings  JSONB
);

-- ─── Indexes ─────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_tournaments_date               ON tournaments(date);
CREATE INDEX IF NOT EXISTS idx_tournaments_format             ON tournaments(format);
CREATE INDEX IF NOT EXISTS idx_tournaments_generation_format  ON tournaments(generation, format);
CREATE INDEX IF NOT EXISTS idx_teams_tournament               ON teams(tournament_id);
CREATE INDEX IF NOT EXISTS idx_teams_player                   ON teams(player_id);
CREATE INDEX IF NOT EXISTS idx_pokemon_sets_team              ON pokemon_sets(team_id);
CREATE INDEX IF NOT EXISTS idx_pokemon_sets_species           ON pokemon_sets(species);
CREATE INDEX IF NOT EXISTS idx_moves_pokemon_set              ON moves(pokemon_set_id);
CREATE INDEX IF NOT EXISTS idx_matches_tournament             ON matches(tournament_id);
CREATE INDEX IF NOT EXISTS idx_match_participants_match       ON match_participants(match_id);
CREATE INDEX IF NOT EXISTS idx_match_participants_team        ON match_participants(team_id);
CREATE INDEX IF NOT EXISTS idx_tournament_standings_tournament ON tournament_standings(tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_standings_player    ON tournament_standings(player_id);

-- ─── Row-Level Security ───────────────────────────────────────────────────────
-- All normalized tables are publicly readable (anon key).
-- limitless_api_raw_data is admin-only (service_role bypasses RLS automatically).

ALTER TABLE tournaments           ENABLE ROW LEVEL SECURITY;
ALTER TABLE players               ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE pokemon_sets          ENABLE ROW LEVEL SECURITY;
ALTER TABLE moves                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches               ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_participants    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_standings  ENABLE ROW LEVEL SECURITY;
ALTER TABLE limitless_api_raw_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_read" ON tournaments;
DROP POLICY IF EXISTS "anon_read" ON players;
DROP POLICY IF EXISTS "anon_read" ON teams;
DROP POLICY IF EXISTS "anon_read" ON pokemon_sets;
DROP POLICY IF EXISTS "anon_read" ON moves;
DROP POLICY IF EXISTS "anon_read" ON matches;
DROP POLICY IF EXISTS "anon_read" ON match_participants;
DROP POLICY IF EXISTS "anon_read" ON tournament_standings;

CREATE POLICY "anon_read" ON tournaments          FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON players              FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON teams                FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON pokemon_sets         FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON moves                FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON matches              FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON match_participants   FOR SELECT TO anon USING (true);
CREATE POLICY "anon_read" ON tournament_standings FOR SELECT TO anon USING (true);
